name: ns_firebase_utils
description: Set of methods/extentions for firebase that makes using framework in a much easier and clean way also adds additional functionality
version: 0.0.3
homepage: https://github.com/ajaynonstopio/ns_firebase_utils

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #<editor-fold desc="FIREBASE">
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.2
  cloud_functions: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^1.0.0
  firebase_dynamic_links: ^0.8.0
  firebase_remote_config: ^0.6.0
  firebase_performance: ^0.6.0
  #</editor-fold>

  #<editor-fold desc="FIREBASE TEST">
  cloud_firestore_mocks: ^0.8.0
  #</editor-fold>


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
